version: '3'

services:
  # web:
  #   image: api_banking
  #   container_name: api-bank-web
  #   build: .
  #   command: mix phx.server
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "4000:4000"
  #   links:
  #     - postgres

  postgres:
    image: postgres
    container_name: api-bank-postgresql
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "api_banking_dev"
      POSTGRES_PASSWORD: "postgres"
    volumes: 
      - ./createExtension.sh:/docker-entrypoint-initdb.d/createExtension.sh